// Generated by the protocol buffer compiler.  DO NOT EDIT!

#define INTERNAL_SUPPRESS_PROTOBUF_FIELD_DEPRECATION
#include "Documents/DocumentProtocol.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)

namespace Diadoc {
namespace Api {
namespace Proto {
namespace Documents {

namespace {

const ::google::protobuf::Descriptor* DocumentProtocol_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  DocumentProtocol_reflection_ = NULL;

}  // namespace


void protobuf_AssignDesc_Documents_2fDocumentProtocol_2eproto() {
  protobuf_AddDesc_Documents_2fDocumentProtocol_2eproto();
  const ::google::protobuf::FileDescriptor* file =
    ::google::protobuf::DescriptorPool::generated_pool()->FindFileByName(
      "Documents/DocumentProtocol.proto");
  GOOGLE_CHECK(file != NULL);
  DocumentProtocol_descriptor_ = file->message_type(0);
  static const int DocumentProtocol_offsets_[2] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(DocumentProtocol, printform_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(DocumentProtocol, signature_),
  };
  DocumentProtocol_reflection_ =
    new ::google::protobuf::internal::GeneratedMessageReflection(
      DocumentProtocol_descriptor_,
      DocumentProtocol::default_instance_,
      DocumentProtocol_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(DocumentProtocol, _has_bits_[0]),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(DocumentProtocol, _unknown_fields_),
      -1,
      ::google::protobuf::DescriptorPool::generated_pool(),
      ::google::protobuf::MessageFactory::generated_factory(),
      sizeof(DocumentProtocol));
}

namespace {

GOOGLE_PROTOBUF_DECLARE_ONCE(protobuf_AssignDescriptors_once_);
inline void protobuf_AssignDescriptorsOnce() {
  ::google::protobuf::GoogleOnceInit(&protobuf_AssignDescriptors_once_,
                 &protobuf_AssignDesc_Documents_2fDocumentProtocol_2eproto);
}

void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
    DocumentProtocol_descriptor_, &DocumentProtocol::default_instance());
}

}  // namespace

void protobuf_ShutdownFile_Documents_2fDocumentProtocol_2eproto() {
  delete DocumentProtocol::default_instance_;
  delete DocumentProtocol_reflection_;
}

void protobuf_AddDesc_Documents_2fDocumentProtocol_2eproto() {
  static bool already_here = false;
  if (already_here) return;
  already_here = true;
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
    "\n Documents/DocumentProtocol.proto\022\032Diad"
    "oc.Api.Proto.Documents\"8\n\020DocumentProtoc"
    "ol\022\021\n\tPrintForm\030\001 \002(\014\022\021\n\tSignature\030\002 \002(\014", 120);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "Documents/DocumentProtocol.proto", &protobuf_RegisterTypes);
  DocumentProtocol::default_instance_ = new DocumentProtocol();
  DocumentProtocol::default_instance_->InitAsDefaultInstance();
  ::google::protobuf::internal::OnShutdown(&protobuf_ShutdownFile_Documents_2fDocumentProtocol_2eproto);
}

// Force AddDescriptors() to be called at static initialization time.
struct StaticDescriptorInitializer_Documents_2fDocumentProtocol_2eproto {
  StaticDescriptorInitializer_Documents_2fDocumentProtocol_2eproto() {
    protobuf_AddDesc_Documents_2fDocumentProtocol_2eproto();
  }
} static_descriptor_initializer_Documents_2fDocumentProtocol_2eproto_;


// ===================================================================

#ifndef _MSC_VER
const int DocumentProtocol::kPrintFormFieldNumber;
const int DocumentProtocol::kSignatureFieldNumber;
#endif  // !_MSC_VER

DocumentProtocol::DocumentProtocol()
  : ::google::protobuf::Message() {
  SharedCtor();
}

void DocumentProtocol::InitAsDefaultInstance() {
}

DocumentProtocol::DocumentProtocol(const DocumentProtocol& from)
  : ::google::protobuf::Message() {
  SharedCtor();
  MergeFrom(from);
}

void DocumentProtocol::SharedCtor() {
  _cached_size_ = 0;
  printform_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
  signature_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

DocumentProtocol::~DocumentProtocol() {
  SharedDtor();
}

void DocumentProtocol::SharedDtor() {
  if (printform_ != &::google::protobuf::internal::kEmptyString) {
    delete printform_;
  }
  if (signature_ != &::google::protobuf::internal::kEmptyString) {
    delete signature_;
  }
  if (this != default_instance_) {
  }
}

void DocumentProtocol::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* DocumentProtocol::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return DocumentProtocol_descriptor_;
}

const DocumentProtocol& DocumentProtocol::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_Documents_2fDocumentProtocol_2eproto();  return *default_instance_;
}

DocumentProtocol* DocumentProtocol::default_instance_ = NULL;

DocumentProtocol* DocumentProtocol::New() const {
  return new DocumentProtocol;
}

void DocumentProtocol::Clear() {
  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    if (has_printform()) {
      if (printform_ != &::google::protobuf::internal::kEmptyString) {
        printform_->clear();
      }
    }
    if (has_signature()) {
      if (signature_ != &::google::protobuf::internal::kEmptyString) {
        signature_->clear();
      }
    }
  }
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  mutable_unknown_fields()->Clear();
}

bool DocumentProtocol::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!(EXPRESSION)) return false
  ::google::protobuf::uint32 tag;
  while ((tag = input->ReadTag()) != 0) {
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // required bytes PrintForm = 1;
      case 1: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_LENGTH_DELIMITED) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadBytes(
                input, this->mutable_printform()));
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(18)) goto parse_Signature;
        break;
      }
      
      // required bytes Signature = 2;
      case 2: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_LENGTH_DELIMITED) {
         parse_Signature:
          DO_(::google::protobuf::internal::WireFormatLite::ReadBytes(
                input, this->mutable_signature()));
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectAtEnd()) return true;
        break;
      }
      
      default: {
      handle_uninterpreted:
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          return true;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, mutable_unknown_fields()));
        break;
      }
    }
  }
  return true;
#undef DO_
}

void DocumentProtocol::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // required bytes PrintForm = 1;
  if (has_printform()) {
    ::google::protobuf::internal::WireFormatLite::WriteBytes(
      1, this->printform(), output);
  }
  
  // required bytes Signature = 2;
  if (has_signature()) {
    ::google::protobuf::internal::WireFormatLite::WriteBytes(
      2, this->signature(), output);
  }
  
  if (!unknown_fields().empty()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        unknown_fields(), output);
  }
}

::google::protobuf::uint8* DocumentProtocol::SerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // required bytes PrintForm = 1;
  if (has_printform()) {
    target =
      ::google::protobuf::internal::WireFormatLite::WriteBytesToArray(
        1, this->printform(), target);
  }
  
  // required bytes Signature = 2;
  if (has_signature()) {
    target =
      ::google::protobuf::internal::WireFormatLite::WriteBytesToArray(
        2, this->signature(), target);
  }
  
  if (!unknown_fields().empty()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        unknown_fields(), target);
  }
  return target;
}

int DocumentProtocol::ByteSize() const {
  int total_size = 0;
  
  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    // required bytes PrintForm = 1;
    if (has_printform()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::BytesSize(
          this->printform());
    }
    
    // required bytes Signature = 2;
    if (has_signature()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::BytesSize(
          this->signature());
    }
    
  }
  if (!unknown_fields().empty()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        unknown_fields());
  }
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void DocumentProtocol::MergeFrom(const ::google::protobuf::Message& from) {
  GOOGLE_CHECK_NE(&from, this);
  const DocumentProtocol* source =
    ::google::protobuf::internal::dynamic_cast_if_available<const DocumentProtocol*>(
      &from);
  if (source == NULL) {
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
    MergeFrom(*source);
  }
}

void DocumentProtocol::MergeFrom(const DocumentProtocol& from) {
  GOOGLE_CHECK_NE(&from, this);
  if (from._has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    if (from.has_printform()) {
      set_printform(from.printform());
    }
    if (from.has_signature()) {
      set_signature(from.signature());
    }
  }
  mutable_unknown_fields()->MergeFrom(from.unknown_fields());
}

void DocumentProtocol::CopyFrom(const ::google::protobuf::Message& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void DocumentProtocol::CopyFrom(const DocumentProtocol& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool DocumentProtocol::IsInitialized() const {
  if ((_has_bits_[0] & 0x00000003) != 0x00000003) return false;
  
  return true;
}

void DocumentProtocol::Swap(DocumentProtocol* other) {
  if (other != this) {
    std::swap(printform_, other->printform_);
    std::swap(signature_, other->signature_);
    std::swap(_has_bits_[0], other->_has_bits_[0]);
    _unknown_fields_.Swap(&other->_unknown_fields_);
    std::swap(_cached_size_, other->_cached_size_);
  }
}

::google::protobuf::Metadata DocumentProtocol::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = DocumentProtocol_descriptor_;
  metadata.reflection = DocumentProtocol_reflection_;
  return metadata;
}


// @@protoc_insertion_point(namespace_scope)

}  // namespace Documents
}  // namespace Proto
}  // namespace Api
}  // namespace Diadoc

// @@protoc_insertion_point(global_scope)
